# Site settings
title: DataExplore blog

email: farrell.damien@gmail.com

description: > # this means to ignore newlines until "baseurl:"
 DataExplore blog and other random items.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://dmnfarrell.github.io" # the base hostname & protocol for your site

github_username:  dmnfarrell

# Build settings
markdown: rdiscount
highlighter: true
